### ISSUE TITLE
Feat: 회원 CRUD 기능 

### ISSUE THREAD

**Issue by chltjsdl0119** [Encore-Hub/BackEnd#10]
# Description
- 회원 CRUD 기능 구현
# Todo
- [ ] 회원 조회 로직 작성
- [ ] 회원 수정 로직 작성
- [ ] 회원 탈퇴 로직 작성
