### ISSUE TITLE
Feat: CI/CD 구축

### ISSUE THREAD

**Issue by seohee-P** [Encore-Hub/BackEnd#31]
# Description
- GitHub Actions + Docker + EC2로 CI/CD 구축

# Todo
- [x] .github/workflows/X.yml 파일 작성하기
- [x]  Docker 파일 작성하기
- [x] 전에 있는 CI/CD 코드 지우기

**Comment by seohee-P** [comment]
구현 완료했습니다.
